name: corbado_demo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  oktoast: ^3.3.0
  convert: ^3.1.1
  shelf: ^1.4.0
  go_router: ^6.5.7
  corbado_auth: ^1.0.0
  passkeys: ^1.0.0
  corbado_frontend_api_client: ^1.0.0
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
